### ISSUE TITLE
Сделал первую карту! Проверьте код, убедитесь, что все гуд

### ISSUE THREAD

**Issue by SstraD-s** [dimmkin/tpro-ddz-packman#10]
Код лежит в ветке menu-Vova в каталоге Card_1

Должна получиться вот такая красота) 
![Снимок экрана от 2023-11-13 22-48-15](https://github.com/dimmkin/tpro-ddz-packman/assets/77076210/f979f1cc-897d-4459-b37b-b2e72d4bdea2)

**Comment by dimmkin** [comment]
Вроде все ок, ошибок не вижу

**Comment by dno442** [comment]
Карта отличная ошибок не нашёд
