### ISSUE TITLE
Измениение для правил проекта

### ISSUE THREAD

**Issue by dno442** [dimmkin/tpro-ddz-packman#14]
### Считаю что нужно добавить пункты в правила к проекту
1)  Все фотографии и  шрифты используемые в проекте хронить в директория image и font соотвествено 
2) Так же соблюдать одинаковые названия при подписи фотографий и файлов в проекте

**Comment by SstraD-s** [comment]
Okey

**Comment by dimmkin** [comment]
Согласен
