### ISSUE TITLE
Сделал фоновую музыку и добавил отсчет по времени перед запуском карты

### ISSUE THREAD

**Issue by SstraD-s** [dimmkin/tpro-ddz-packman#19]
Код лежит в ветке menu-music-Vova, если что-то нужно подправить, сообщите

**Comment by dno442** [comment]
Посмотрел всё отлично

**Comment by dno442** [comment]
Думаю можно сделать так чтобы экран до запуска игры выводился в окошке где будет происходить сама игра

**Comment by SstraD-s** [comment]
Хм, да думаю ты прав. Исправлю
