### ISSUE TITLE
Начало игрового процесса

### ISSUE THREAD

**Issue by dimmkin** [dimmkin/tpro-ddz-packman#20]
Сделал отрисовку поля и перемещение пакмана по полю

Код лежит в ветке game_process-dima в директориях /include и /src

Если что-то не так, дайте знать

**Comment by dno442** [comment]
Написал todo в файле src/settings.cpp и include/menuBase.h

**Comment by SstraD-s** [comment]
Код посмотрел, кроме ранее отмеченных todo-шек замечаний нет
