### ISSUE TITLE
Проверьте мой код для меню

### ISSUE THREAD

**Issue by dimmkin** [dimmkin/tpro-ddz-packman#3]
Файлы menu.h и menu.cpp

В menu.h написал класс Menu, в menu.cpp определил конструктор класса и методы передвижения по меню и её отрисовки

Остальные методы класса в процессе разработки

**Comment by dno442** [comment]
Проверил код всё отлично

**Comment by dimmkin** [comment]
Ну хорошо тогда, сейчас будем мерджить в ветку menu
