### ISSUE TITLE
Проверьте, почему просит принудительно завершить работу

### ISSUE THREAD

**Issue by SstraD-s** [dimmkin/tpro-ddz-packman#4]
Код впринципе рабочий, но секунд 7

**Comment by SstraD-s** [comment]
код лежит в ветке menu-Vova

**Comment by dimmkin** [comment]
А в какой директории, не могу понять :\

**Comment by SstraD-s** [comment]
Ой, забыл написать

Код лежит в директории Card_1

**Comment by dimmkin** [comment]
Вижу) Сейчас посмотрю, что не так

**Comment by dimmkin** [comment]
Так сразу и не разберешься, вчитаюсь в код завтра

**Comment by SstraD-s** [comment]
так, с кодом я разобрался, все работает, вопрос закрыт)
