### ISSUE TITLE
Проверьте мой код(меню)

### ISSUE THREAD

**Issue by dimmkin** [dimmkin/tpro-ddz-packman#5]
## Код лежит в файлах(в ветке menu-dima):

**1)main.cpp
2)menu.cpp
3)menu.h
4)bots.cpp
5)bots.h
6)gameselection.cpp
7)gameselection.h
8)maps.cpp
9)maps.h**

Я написал класс для каждого блока меню, в которых пользователь выбирает начальные условия старта игры

В menu.cpp и menu.h находится код, который описывает главное меню, а именно блок: Start, Settings, Exit.
В классе Menu определил методы, которые будут работать для навигации по данному блоку.

Аналогичную работу провел с блоками, которые будут появляться после выбора в меню Start, а именно блоки: выбор типа игры(классическая - 3 раунда или быстра игра - 1 раунд), выбор количества ботов, выбор карты на который будет играть пользователь

Не совсем уверен, в своем коде, хотя все работает, поэтому проверьте его, может можно как-то оптимизировать

**Comment by SstraD-s** [comment]
Проверил код, у тебя есть 4 класса очень похожих. Может попробуешь наследоваться от какого-нибудь одного???

**Comment by dimmkin** [comment]
Согласен, сейчас попробую исправить

**Comment by dno442** [comment]
Думая можно сделать наследование от основного класса Menu, и все другие классы перенести в один файл, чтобы было проще подключать его

**Comment by dimmkin** [comment]
### Исправил код

**Код лежит в (ветка menu-dima):**
1) Директория src:
   а) bots.cpp
   b) maps.cpp
   c) menu.cpp
   d) gameselection.cpp
   e) menuBase.cpp
2) Директория include:
   a) menuBase.h

Создал основной класс MenuBase, в который положил основной функционал игрового меню, дальше создавал классы, наследуемые от данного, получилось более оптимизированно и читабельнее

Посмотрите мой код, вроде все ок, но лучше проверить еще раз)

**Comment by dno442** [comment]
Посмотрел ошибок нет, код написан хорошо

**Comment by SstraD-s** [comment]
Все четко, пуш в ветку menu
